<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Graphical Evaluation: Real Cases • topmodels</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><link href="../extra.css" rel="stylesheet">
<meta property="og:title" content="Graphical Evaluation: Real Cases">
<meta property="og:description" content="topmodels">
<meta property="og:image" content="https://topmodels.R-Forge.R-project.org/logo.png">
<meta name="twitter:card" content="summary">
<meta name="twitter:creator" content="@MoritzNLang">
<meta name="twitter:site" content="@MoritzNLang">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">topmodels</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.1-0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../articles/topmodels.html">Get started</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/graphical_evaluation_methodology.html">Graphical Evaluation: Methodology</a>
    </li>
    <li>
      <a href="../articles/graphical_evaluation_simulations.html">Graphical Evaluation: Simulations</a>
    </li>
    <li>
      <a href="../articles/graphical_evaluation_realcases.html">Graphical Evaluation: Real Cases</a>
    </li>
    <li>
      <a href="../articles/implementation_functions_graphical_evaluation.html">Implementation: Functions for Graphical Evaluation</a>
    </li>
  </ul>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
<li>
  <a href="../contact.html">Contact</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Graphical Evaluation: Real Cases</h1>
                        <h4 class="author">Moritz Lang, Achim Zeileis</h4>
            
      
      
      <div class="hidden name"><code>graphical_evaluation_realcases.Rmd</code></div>

    </div>

    
    
<p>This vignette provides two real cases discussing the graphical evaluation of the marginal and probabilistic calibration of probabilistic regression models. The first example provides a short case study modeling the goals at the 2018 FIFA World Cup employing a Poisson distribution. It is a direct extension of the vignette <a href="https://alexpghayes.github.io/distributions3/dev/articles/poisson.html">“The Poisson Distribution: From Basic Probability Theory to Regression Models”</a> given in <a href="https://github.com/alexpghayes/distributions3"><code>distributions3</code></a>. The second example models 3 day-accumulated precipitation sums using a Logistic distribution censored at zero accounting for non-negative precipitation sums. The use case builds heavily on the vignette <a href="https://cran.r-project.org/web/packages/crch/vignettes/crch.pdf">“Heteroscedastic Censored and Truncated Regression with crch”</a> given in <a href="https://cran.r-project.org/web/packages/crch/"><code>crch</code></a> by <span class="citation">Messner, Mayr, and Zeileis (2016)</span>.</p>
<div id="goals-in-the-2018-fifa-world-cup" class="section level1">
<h1 class="hasAnchor">
<a href="#goals-in-the-2018-fifa-world-cup" class="anchor"></a>Goals in the 2018 FIFA World Cup</h1>
<p>This use-case employs the Poisson distribution for modeling count data along predicted probabilities for the number of goals in soccer matches from the 2018 FIFA World Cup. The full analysis with an illustrative introduction from basic probability theory to regression models using the R package <a href="https://github.com/alexpghayes/distributions3"><code>distributions3</code></a> is given <a href="https://alexpghayes.github.io/distributions3/dev/articles/poisson.html">here</a>.</p>
<p>To investigate the number of goals scored per match in the 2018 FIFA World Cup, the <code>FIFA2018</code> data set provides two rows, one for each team, for each of the 64 matches during the tournament. In the following, we treat the goals scored by the two teams in the same match as independent which is a realistic assumption for this particular data set. We just remark briefly that there are also bivariate generalizations of the Poisson distribution that would allow for correlated observations but which are not considered here.</p>
<p>In addition to the goals, the data set provides some basic meta-information for the matches (an ID, team name abbreviations, type of match, group vs. knockout stage) as well as some further covariates that we will revisit later in this document. The data looks like this:</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"FIFA2018"</span>, package <span class="op">=</span> <span class="st">"distributions3"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">FIFA2018</span><span class="op">)</span></code></pre></div>
<pre><code>##   goals team match type stage logability difference
## 1     5  RUS     1    A group  0.1530732  0.8638406
## 2     0  KSA     1    A group -0.7107673 -0.8638406
## 3     0  EGY     2    A group -0.2066409 -0.4438080
## 4     1  URU     2    A group  0.2371671  0.4438080
## 5     3  RUS     3    A group  0.1530732  0.3597142
## 6     1  EGY     3    A group -0.2066409 -0.3597142</code></pre>
<p>For now, we will focus on the <code>goals</code> variable only. A brief summary yields</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">FIFA2018</span><span class="op">$</span><span class="va">goals</span><span class="op">)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.000   0.000   1.000   1.297   2.000   6.000</code></pre>
<p>showing that the teams scored between <span class="math inline">\(0\)</span> and <span class="math inline">\(6\)</span> goals per match with an average of <span class="math inline">\(\bar y = 1.297\)</span> from the observations <span class="math inline">\(y_i\)</span> (<span class="math inline">\(i = 1, \dots, 128\)</span>). The corresponding table of observed relative frequencies are:</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/proportions.html">prop.table</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">FIFA2018</span><span class="op">$</span><span class="va">goals</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##         0         1         2         3         4         5         6 
## 0.2578125 0.3750000 0.2500000 0.0781250 0.0156250 0.0156250 0.0078125</code></pre>
<p>(Note that in recent versions of R using <code><a href="https://rdrr.io/r/base/proportions.html">proportions()</a></code> rather than <code><a href="https://rdrr.io/r/base/proportions.html">prop.table()</a></code> is recommended.)</p>
<p>This confirms that goals are relatively rare events in a soccer game with each team scoring zero to two goals per match in almost 90 percent of the matches. Below we show that this observed frequency distribution can be approximated very well by a Poisson distribution which can subsequently be used to obtain predicted probabilities for the goals scored in a match.</p>
<div id="from-basic-probability-theory-to-regression-models" class="section level2">
<h2 class="hasAnchor">
<a href="#from-basic-probability-theory-to-regression-models" class="anchor"></a>From basic probability theory to regression models</h2>
<p>In a first step, we simply assume that goals are scored with a constant mean over all teams and fit a single Poisson distribution for the number of goals. To do so, we obtain a point estimate of the Poisson parameter by using the empirical mean <span class="math inline">\(\hat \lambda = \bar y = 1.297\)</span> and set up the corresponding distribution object:</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">p_const</span> <span class="op">&lt;-</span> <span class="fu">distributions3</span><span class="fu">::</span><span class="fu"><a href="https://alexpghayes.github.io/distributions3/reference/Poisson.html">Poisson</a></span><span class="op">(</span>lambda <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">FIFA2018</span><span class="op">$</span><span class="va">goals</span><span class="op">)</span><span class="op">)</span>
<span class="va">p_const</span></code></pre></div>
<pre><code>## [1] "Poisson distribution (lambda = 1.297)"</code></pre>
<p>This actually corresponds to the maximum likelihood estimator for this distribution fitting a generalized linear model (GLM) to the data that links the expected number of goals per team/match <span class="math inline">\(\lambda_i\)</span> to the linear predictor <span class="math inline">\(x_i^\top \beta\)</span> with regressor vector <span class="math inline">\(x_i^\top\)</span> and corresponding coefficient vector <span class="math inline">\(\beta\)</span> using a log-link: <span class="math inline">\(\log(\lambda_i) = x_i^\top \beta\)</span>.</p>
<p>Here, in the simplest case fitting an intercept-only model without further regressors, the regressor vector can be written as <span class="math inline">\(x_i^\top = 1\)</span> and the maximum likelihood estimator <span class="math inline">\(\hat \beta\)</span> with corresponding inference, predictions, residuals, etc. can be obtained using the <code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code> function from base R with <code>family = poisson</code>:</p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">m_ic</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">goals</span> <span class="op">~</span> <span class="fl">1</span>, data <span class="op">=</span> <span class="va">FIFA2018</span>, family <span class="op">=</span> <span class="va">poisson</span><span class="op">)</span>
<span class="va">m_ic</span></code></pre></div>
<pre><code>## 
## Call:  glm(formula = goals ~ 1, family = poisson, data = FIFA2018)
## 
## Coefficients:
## (Intercept)  
##        0.26  
## 
## Degrees of Freedom: 127 Total (i.e. Null);  127 Residual
## Null Deviance:       144.2 
## Residual Deviance: 144.2     AIC: 372.9</code></pre>
<p>The corresponding prediction for the number of goals can be obtained manually from the extracted <code><a href="https://rdrr.io/r/stats/coef.html">coef()</a></code> by applying <code><a href="https://rdrr.io/r/base/Log.html">exp()</a></code> (as the inverse of the log-link).</p>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">lambda_zero</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">m_ic</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">)</span>
<span class="va">lambda_zero</span></code></pre></div>
<pre><code>## (Intercept) 
##    1.296875</code></pre>
<p>Or equivalently the <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> function can be used with <code>type = "response"</code> in order to get the expected <span class="math inline">\(\hat \lambda_i\)</span> (rather than just the linear predictor <span class="math inline">\(x_i^\top \hat \beta\)</span> that is predicted by default).</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">m_ic</span>, newdata <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>difference <span class="op">=</span> <span class="fl">0</span><span class="op">)</span>, type <span class="op">=</span> <span class="st">"response"</span><span class="op">)</span></code></pre></div>
<pre><code>##        1 
## 1.296875</code></pre>
<p>This yields the same predicted Poisson distribution, identical to <span class="math inline">\(p_const\)</span>, for all teams and matches in this tournament – most likely an incorrect assumption:</p>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">p_ic</span> <span class="op">&lt;-</span> <span class="fu">distributions3</span><span class="fu">::</span><span class="fu"><a href="https://alexpghayes.github.io/distributions3/reference/Poisson.html">Poisson</a></span><span class="op">(</span>lambda <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">m_ic</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">p_ic</span><span class="op">)</span></code></pre></div>
<pre><code>##                                       1                                       2 
## "Poisson distribution (lambda = 1.297)" "Poisson distribution (lambda = 1.297)" 
##                                       3                                       4 
## "Poisson distribution (lambda = 1.297)" "Poisson distribution (lambda = 1.297)" 
##                                       5                                       6 
## "Poisson distribution (lambda = 1.297)" "Poisson distribution (lambda = 1.297)"</code></pre>
<p>To account for different expected performances from the teams in the 2018 FIFA World Cup, the <code>FIFA2018</code> data provides an estimated <code>logability</code> for each team. These have been estimated by <span class="citation">Zeileis, Leitner, and Hornik (2018)</span> prior to the start of the tournament (2018-05-20) based on quoted odds from 26 online bookmakers using the bookmaker consensus model of <span class="citation">Leitner, Zeileis, and Hornik (2010)</span>. The <code>difference</code> in <code>logability</code> between a team and its opponent is a useful predictor for the number of <code>goals</code> scored.</p>
<p>Hence, the intercept-only model <code>m_ic</code> can be extended by using the regressor vector <span class="math inline">\(x_i^\top = (1, \mathtt{difference}_i)\)</span>:</p>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">m_reg</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">goals</span> <span class="op">~</span> <span class="va">difference</span>, data <span class="op">=</span> <span class="va">FIFA2018</span>, family <span class="op">=</span> <span class="va">poisson</span><span class="op">)</span>
<span class="va">m_reg</span></code></pre></div>
<pre><code>## 
## Call:  glm(formula = goals ~ difference, family = poisson, data = FIFA2018)
## 
## Coefficients:
## (Intercept)   difference  
##      0.2127       0.4134  
## 
## Degrees of Freedom: 127 Total (i.e. Null);  126 Residual
## Null Deviance:       144.2 
## Residual Deviance: 128.7     AIC: 359.4</code></pre>
<p>Here, the slope of <span class="math inline">\(0.413\)</span> can be interpreted as an ability elasticity of the number of goals scored. This is because the difference of the log-abilities can also be understood as the log of the ability ratio. Thus, when the ability ratio increases by <span class="math inline">\(1\)</span> percent, the expected number of goals increases approximately by <span class="math inline">\(0.413\)</span> percent.</p>
<p>In comparison to the intercept-only model <code>m_ic</code>, this yields a more realistic outcome providing a different predicted Poisson distribution for each team/match in the tournament. We can set up the vector of all <span class="math inline">\(128\)</span> <code><a href="https://rdrr.io/r/stats/Poisson.html">Poisson()</a></code> distribution objects by extracting the vector of all fitted point estimates <span class="math inline">\((\hat \lambda_1, \dots, \hat \lambda_{128})^\top\)</span>:</p>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">p_reg</span> <span class="op">&lt;-</span> <span class="fu">distributions3</span><span class="fu">::</span><span class="fu"><a href="https://alexpghayes.github.io/distributions3/reference/Poisson.html">Poisson</a></span><span class="op">(</span>lambda <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">m_reg</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">p_reg</span><span class="op">)</span></code></pre></div>
<pre><code>##                                        1 
## "Poisson distribution (lambda = 1.7680)" 
##                                        2 
## "Poisson distribution (lambda = 0.8655)" 
##                                        3 
## "Poisson distribution (lambda = 1.0297)" 
##                                        4 
## "Poisson distribution (lambda = 1.4862)" 
##                                        5 
## "Poisson distribution (lambda = 1.4354)" 
##                                        6 
## "Poisson distribution (lambda = 1.0661)"</code></pre>
</div>
<div id="model-evaluation-marginal-calibration" class="section level2">
<h2 class="hasAnchor">
<a href="#model-evaluation-marginal-calibration" class="anchor"></a>Model evaluation: Marginal calibration</h2>
<p>Marginal calibration is generally concerned with whether the observed frequencies match the frequencies expected by the model. For discrete observations, frequencies for the observations themselves can be considered; for continuous observations or more generally, frequencies for intervals of observations are being used. Here, the expected frequencies are computed by differences between the predictive CDFs <span class="math inline">\(F( \cdot )\)</span>, evaluated at the interval breaks. Hence, marginal calibration is always obtained on the observation scale compared to the probabilistic calibration performed on the probability scale. This makes it especially useful for evaluating count data models which predictions are often close to zero.</p>
<p>For evaluating the marginal calibration of the Poisson models for the number of <code>goals</code> scored, we compute the expected absolute frequencies by averaging across the expectations per team/match from both regression model and compare these with the observed absolute frequencies:</p>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">observed</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">FIFA2018</span><span class="op">$</span><span class="va">goals</span><span class="op">)</span>
<span class="va">expected_ic</span> <span class="op">&lt;-</span> <span class="fu">distributions3</span><span class="fu">::</span><span class="fu"><a href="https://alexpghayes.github.io/distributions3/reference/pdf.html">pdf</a></span><span class="op">(</span><span class="va">p_ic</span>, <span class="fl">0</span><span class="op">:</span><span class="fl">6</span><span class="op">)</span>
<span class="va">expected_ic</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">colMeans</a></span><span class="op">(</span><span class="va">expected_ic</span><span class="op">)</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">observed</span><span class="op">)</span>
<span class="va">expected_reg</span> <span class="op">&lt;-</span> <span class="fu">distributions3</span><span class="fu">::</span><span class="fu"><a href="https://alexpghayes.github.io/distributions3/reference/pdf.html">pdf</a></span><span class="op">(</span><span class="va">p_reg</span>, <span class="fl">0</span><span class="op">:</span><span class="fl">6</span><span class="op">)</span>
<span class="va">expected_reg</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">colMeans</a></span><span class="op">(</span><span class="va">expected_reg</span><span class="op">)</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">observed</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">observed</span>, <span class="va">expected_ic</span>, <span class="va">expected_reg</span><span class="op">)</span> </code></pre></div>
<pre><code>##   observed expected_ic expected_reg
## 0       33  34.9932527    37.679930
## 1       48  45.3818746    43.541948
## 2       32  29.4273093    27.450378
## 3       10  12.7211806    12.574218
## 4        2   4.1244453     4.684102
## 5        2   1.0697780     1.501012
## 6        1   0.2312281     0.426588</code></pre>
<p>Graphically, this comparison can be shown as a so-called <em>rootogram</em> <span class="citation">(Kleiber and Zeileis 2016)</span> where the gray bars represent the observed frequencies overlayed by the expected frequencies as a red line. By using the function <code><a href="../reference/rootogram.html">rootogram()</a></code>, we can reproduce the previous results plugging in the model objects <code>m_ic</code> and <code>m_reg</code>:</p>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">r1</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/rootogram.html">rootogram</a></span><span class="op">(</span><span class="va">m_ic</span>, fitted <span class="op">=</span> <span class="cn">TRUE</span>, style <span class="op">=</span> <span class="st">"standing"</span>, scale <span class="op">=</span> <span class="st">"raw"</span>, ref <span class="op">=</span> <span class="cn">FALSE</span>, plot <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>
<span class="va">r2</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/rootogram.html">rootogram</a></span><span class="op">(</span><span class="va">m_reg</span>, fitted <span class="op">=</span> <span class="cn">TRUE</span>, style <span class="op">=</span> <span class="st">"standing"</span>, scale <span class="op">=</span> <span class="st">"raw"</span>, ref <span class="op">=</span> <span class="cn">FALSE</span>, plot <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">r1</span>, <span class="va">r2</span><span class="op">)</span></code></pre></div>
<pre><code>## A `rootogram` object with `scale = 'raw'` and `style = 'standing'`
## 
##    observed   expected mid width group
## 1        33 34.9932527   0   0.9     1
## 2        48 45.3818746   1   0.9     1
## 3        32 29.4273093   2   0.9     1
## 4        10 12.7211806   3   0.9     1
## 5         2  4.1244453   4   0.9     1
## 6         2  1.0697780   5   0.9     1
## 7         1  0.2312281   6   0.9     1
## 8        33 37.6799296   0   0.9     2
## 9        48 43.5419481   1   0.9     2
## 10       32 27.4503775   2   0.9     2
## 11       10 12.5742178   3   0.9     2
## 12        2  4.6841019   4   0.9     2
## 13        2  1.5010116   5   0.9     2
## 14        1  0.4265880   6   0.9     2</code></pre>
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot2</span><span class="fu">::</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autoplot.html">autoplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">r1</span>, <span class="va">r2</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p><img src="graphical_evaluation_realcases_files/figure-html/unnamed-chunk-12-1.png" width="700"></p>
<p>Further, in order to stabilize the variances of the discrepancies, i.e., putting more focus on discrepancies for small frequencies, we can show the frequencies on a square root scale:</p>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot2</span><span class="fu">::</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autoplot.html">autoplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">r1</span>, <span class="va">r2</span><span class="op">)</span>, scale <span class="op">=</span> <span class="st">"sqrt"</span><span class="op">)</span>  <span class="co"># FIXME: (ML) names got lost</span></code></pre></div>
<p><img src="graphical_evaluation_realcases_files/figure-html/unnamed-chunk-13-1.png" width="700"></p>
<p>In a second step, we employ a so-called <em>hanging rootogram</em> where bars representing the square-root of the observed frequencies are “hanging” from the square-root of the expected frequencies in the red line. Here, the offset around the x-axis compared to a reference line clearly shows the difference between the two frequencies for the intercept-only model <code>m_ic</code> and the full probabilistic model <code>m_reg</code>. For both models the differences are reasonably close to zero indicating a rather good marginal fit:</p>
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot2</span><span class="fu">::</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autoplot.html">autoplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">r1</span>, <span class="va">r2</span><span class="op">)</span>, scale <span class="op">=</span> <span class="st">"sqrt"</span>, style <span class="op">=</span> <span class="st">"hanging"</span>, ref <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>  <span class="co"># FIXME: (ML) names got lost</span></code></pre></div>
<p><img src="graphical_evaluation_realcases_files/figure-html/unnamed-chunk-14-1.png" width="700"></p>
<p>So far we have only evaluated the marginal calibration comparing whether the observed frequencies match the frequencies expected by estimated model on the observational scale. In the next step we will evaluate the probabilistic calibration which is performed on the probability scale.</p>
</div>
<div id="model-evaluation-probabilistic-calibration" class="section level2">
<h2 class="hasAnchor">
<a href="#model-evaluation-probabilistic-calibration" class="anchor"></a>Model evaluation: Probabilistic calibration</h2>
<p>Probabilistic calibration is usually assessed using probability integral transform (PIT) values <span class="citation">(Dawid 1984; Diebold, Gunther, and Tay 1998; Gneiting, Balabdaoui, and Raftery 2007)</span> or so-called PIT residuals <span class="citation">(Warton 2017)</span>. These are simply the predictive cumulative distribution function (CDF) evaluated at the observations</p>
<p><span class="math display">\[u_i = F(y_i | \, \hat{\boldsymbol{\theta}}_i),\]</span></p>
<p>where <span class="math inline">\(F( \cdot )\)</span> denotes the CDF of the modeled distribution <span class="math inline">\(f( \cdot )\)</span> with estimated parameters <span class="math inline">\(\hat{\boldsymbol{\theta}}_{i}\)</span>. PIT residuals have the desirable property, that if the model is a good approximation to the true data-generating process, i.e., the observation is drawn from the predictive distribution, the PIT residuals <span class="math inline">\(u_i\)</span> are approximately uniformly distributed on <span class="math inline">\([0, 1]\)</span> for continuous predictive distributions <span class="math inline">\(F( \cdot )\)</span>. Plotting the histogram of the PIT residuals and checking for uniformity is therefore a common empirical way of checking for calibration:</p>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">p1</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/pithist.html">pithist</a></span><span class="op">(</span><span class="va">m_reg</span><span class="op">)</span></code></pre></div>
<p><img src="graphical_evaluation_realcases_files/figure-html/unnamed-chunk-15-1.png" width="700"></p>
<p>To focus more on violations of the distributional assumption in the tails of the distribution, PIT residuals can also be transformed to the normal scale or another scale if preferred. This allows the extreme values to be spread more widely, so that less values are included in the outer intervals. However, this has the drawback that detecting misspecification is more complicated than checking for uniformity:</p>
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">p2</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/pithist.html">pithist</a></span><span class="op">(</span><span class="va">m_reg</span>, trafo <span class="op">=</span> <span class="va">qnorm</span>, type <span class="op">=</span> <span class="st">"random"</span>, simint <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="co"># `type = "expected"` does not work, check!</span></code></pre></div>
<p><img src="graphical_evaluation_realcases_files/figure-html/unnamed-chunk-16-1.png" width="700"></p>
<p>Discretization, i.e., the representation of values in intervals, has the advantage that it usually improves the readability of graphical representations. However, discretization can also hide certain misspecifications: breakpoints are often quite arbitrary and can mask misspecifications of relatively few but extreme values in the outer tails of the distribution. Here, classical <em>Q-Q plots</em> are clearly superior to PIT histograms:</p>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">q1</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/qqrplot.html">qqrplot</a></span><span class="op">(</span><span class="va">m_reg</span>, confint <span class="op">=</span> <span class="st">"line"</span>, simint <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<p><img src="graphical_evaluation_realcases_files/figure-html/unnamed-chunk-17-1.png" width="700"></p>
<p>Since small to medium deviations are nevertheless difficult to detect in <em>Q-Q plots</em>, untilting the plot makes detecting pattern of departure from a now horizontal line much easier. Here, expected quantiles are subtracted from the observed quantiles:</p>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">w1</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/wormplot.html">wormplot</a></span><span class="op">(</span><span class="va">m_reg</span>, confint <span class="op">=</span> <span class="st">"line"</span>, simint <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<p><img src="graphical_evaluation_realcases_files/figure-html/unnamed-chunk-18-1.png" width="700"></p>
<p>This so-called de-trended <em>Q-Q plot</em> is best known as <em>worm plot</em> <span class="citation">(Buuren and Fredriks 2001)</span>.</p>
</div>
</div>
<div id="precipitation-forecasts" class="section level1">
<h1 class="hasAnchor">
<a href="#precipitation-forecasts" class="anchor"></a>Precipitation forecasts</h1>
<p>This use-case discusses a weather forecast example application of censored regression models. The example is taken from the vignette <a href="https://cran.r-project.org/web/packages/crch/vignettes/crch.pdf">“Heteroscedastic Censored and Truncated Regression with crch”</a> provided for the package <a href="https://cran.r-project.org/web/packages/crch/"><code>crch</code></a> by <span class="citation">Messner, Mayr, and Zeileis (2016)</span>.</p>
<p>Weather forecasts are usually based on numerical weather prediction (NWP) models, which take the current state of the atmosphere and calculate future weather by numerically simulating the main atmospheric processes. However, due to uncertain initial conditions and unknown or unresolved processes, these numerical predictions are always subject to errors. To estimate these errors, many weather centers produce what are called ensemble forecasts: multiple NWP runs that use different initial conditions and model formulations. Unfortunately, these ensemble forecasts cannot account for all sources of error, so they are often still biased and uncalibrated. Therefore, they are often calibrated and corrected for systematic errors through statistical post-processing.</p>
<p>One popular post-processing method is heteroscedastic linear regression where the ensemble mean is used as regressor for the location and the ensemble standard deviation or variance is used as regressor for the scale <span class="citation">(Gneiting et al. 2005)</span>. The following example applies heteroscedastic censored regression with a logistic distribution assumption to precipitation data in Innsbruck (Austria).</p>
<p>The <code>RainIbk</code> data set contains observed 3 day-accumulated precipitation amounts (<code>rain</code>) and the corresponding 11 member ensemble forecasts of total accumulated precipitation amount between 5 and 8 days in advance (<code>rainfc.1</code>, <code>rainfc.2</code>, … <code>rainfc.11</code>). In previous studies it has been shown that it is of advantage to model the square root of precipitation rather than precipitation itself. Thus all precipitation amounts are square rooted before ensemble mean and standard deviation are derived. Furthermore, events with no variation in the ensemble are omitted:</p>
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"RainIbk"</span>, package <span class="op">=</span> <span class="st">"crch"</span><span class="op">)</span>

<span class="va">RainIbk</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">RainIbk</span><span class="op">)</span>
<span class="va">RainIbk</span><span class="op">$</span><span class="va">ensmean</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="va">RainIbk</span><span class="op">[</span>,<span class="fu"><a href="https://rdrr.io/r/base/grep.html">grep</a></span><span class="op">(</span><span class="st">'^rainfc'</span>,<span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">RainIbk</span><span class="op">)</span><span class="op">)</span><span class="op">]</span>, <span class="fl">1</span>, <span class="va">mean</span><span class="op">)</span>
<span class="va">RainIbk</span><span class="op">$</span><span class="va">enssd</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="va">RainIbk</span><span class="op">[</span>,<span class="fu"><a href="https://rdrr.io/r/base/grep.html">grep</a></span><span class="op">(</span><span class="st">'^rainfc'</span>,<span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">RainIbk</span><span class="op">)</span><span class="op">)</span><span class="op">]</span>, <span class="fl">1</span>, <span class="va">sd</span><span class="op">)</span>
<span class="va">RainIbk</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">RainIbk</span>, <span class="va">enssd</span> <span class="op">&gt;</span> <span class="fl">0</span><span class="op">)</span></code></pre></div>
<div id="from-linear-regression-to-distributional-regression-models" class="section level2">
<h2 class="hasAnchor">
<a href="#from-linear-regression-to-distributional-regression-models" class="anchor"></a>From linear regression to distributional regression models</h2>
<p>For comparison we fit a homoscedastic linear regression model using the least squares approach for <code>rain</code> with <code>ensmean</code> as regressor. As a more appropriate model for <code>rain</code> accounting for non-negative precipitation sums, we fit a hetereoscedastic censored model assuming an underlying logistic response distribution with <code>ensmean</code> as regressor for the location and <code><a href="https://rdrr.io/r/base/Log.html">log(enssd)</a></code> as regressor for the scale:</p>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## linear model</span>
<span class="va">m_lm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">rain</span> <span class="op">~</span> <span class="va">ensmean</span>, data <span class="op">=</span> <span class="va">RainIbk</span><span class="op">)</span>

<span class="co">## heteroscedastic censored regression with a logistic distribution assumption</span>
<span class="va">m_hclog</span> <span class="op">&lt;-</span> <span class="fu">crch</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/crch/man/crch.html">crch</a></span><span class="op">(</span><span class="va">rain</span> <span class="op">~</span> <span class="va">ensmean</span> <span class="op">|</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">enssd</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">RainIbk</span>, left <span class="op">=</span> <span class="fl">0</span>,
  dist <span class="op">=</span> <span class="st">"logistic"</span><span class="op">)</span></code></pre></div>
<p>In the scatterplot of <code>rain</code> against <code>ensmean</code> it can be seen, that precipitation is clearly non-negative with many zero observations. Thus the censored regression model <code>m_hclog</code> is more suitable than the linear regression model to estimate the underlying relationship:</p>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">rain</span> <span class="op">~</span> <span class="va">ensmean</span>, data <span class="op">=</span> <span class="va">RainIbk</span>, pch <span class="op">=</span> <span class="fl">19</span>, col <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/grDevices/gray.html">gray</a></span><span class="op">(</span><span class="fl">0</span>, alpha <span class="op">=</span> <span class="fl">0.2</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">m_lm</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">2</span><span class="op">]</span>, col <span class="op">=</span> <span class="fl">3</span>, lwd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">m_hclog</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">2</span><span class="op">]</span>, col <span class="op">=</span> <span class="fl">4</span>, lwd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/graphics/legend.html">legend</a></span><span class="op">(</span><span class="st">"topright"</span>, lwd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">1</span><span class="op">)</span>, lty <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">1</span><span class="op">)</span>, col <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">4</span><span class="op">)</span>, 
  <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"m_lm"</span>, <span class="st">"m_hclog"</span><span class="op">)</span>, bty <span class="op">=</span> <span class="st">"n"</span><span class="op">)</span></code></pre></div>
<p><img src="graphical_evaluation_realcases_files/figure-html/unnamed-chunk-19-1.png" width="700"></p>
</div>
<div id="model-evaluation-marginal-calibration-1" class="section level2">
<h2 class="hasAnchor">
<a href="#model-evaluation-marginal-calibration-1" class="anchor"></a>Model evaluation: Marginal calibration</h2>
<p>The significant underfitting of zero observations is also very apparent in the <em>rootogramm</em> of the linear model, as it does not correctly account for the point mass at zero. Additionally, a weak wavelike pattern indicates a slight overfitting of precipitation sums between zero and 5mm and an underfitting of precipitation sums above. In contrast, the censored logistic regression <code>m_hclog</code> provides a pretty good marginal fit, where the expected squared frequencies closely match the squared observed frequencies:</p>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">r1</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/rootogram.html">rootogram</a></span><span class="op">(</span><span class="va">m_lm</span>, plot <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>
<span class="va">r2</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/rootogram.html">rootogram</a></span><span class="op">(</span><span class="va">m_hclog</span>, plot <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>

<span class="fu">ggplot2</span><span class="fu">::</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autoplot.html">autoplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">r1</span>, <span class="va">r2</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p><img src="graphical_evaluation_realcases_files/figure-html/unnamed-chunk-20-1.png" width="700"></p>
</div>
<div id="model-evaluation-probabilistic-calibration-1" class="section level2">
<h2 class="hasAnchor">
<a href="#model-evaluation-probabilistic-calibration-1" class="anchor"></a>Model evaluation: Probabilistic calibration</h2>
<p>The <em>PIT histogram</em> of the linear model <code>m_lm</code> is skewed, indicating a misfit in terms of the probabilistic calibration, whereas the <em>PIT histogram</em> of the linear model is rather uniformly distributed.</p>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">p1</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/pithist.html">pithist</a></span><span class="op">(</span><span class="va">m_lm</span>, plot <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>
<span class="va">p2</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/pithist.html">pithist</a></span><span class="op">(</span><span class="va">m_hclog</span>, plot <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>

<span class="fu">ggplot2</span><span class="fu">::</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autoplot.html">autoplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">p1</span>, <span class="va">p2</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p><img src="graphical_evaluation_realcases_files/figure-html/unnamed-chunk-21-1.png" width="700"></p>
<p>For a better comparison of the two model fits, alternatively a line-style <em>PIT histogram</em> can also be shown:</p>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot2</span><span class="fu">::</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autoplot.html">autoplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">p1</span>, <span class="va">p2</span><span class="op">)</span>, colour <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">4</span><span class="op">)</span>, style <span class="op">=</span> <span class="st">"line"</span>, single_graph <span class="op">=</span> <span class="cn">TRUE</span>, confint_col <span class="op">=</span> <span class="fl">1</span>, confint <span class="op">=</span> <span class="st">"line"</span>, ref <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<p><img src="graphical_evaluation_realcases_files/figure-html/unnamed-chunk-22-1.png" width="700"></p>
<p>To further analyse the misfit of the linear model in terms of probabilistic calibration, we transform the PIT residuals to the normal scale and increase the number of breaks in the <em>PIT histogram</em>. Transforming to the normal scale spreads the values at the tails of the distribution further apart, and increasing the breaks prevents potential masking of small scale patterns.</p>
<p>We can see that the distribution of PIT residuals is right skewed with more values between -2 and 0, but less values between 0 and 2 compared to the standard normal distribution:</p>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/pithist.html">pithist</a></span><span class="op">(</span><span class="va">m_lm</span>, breaks <span class="op">=</span> <span class="fl">50</span>, trafo <span class="op">=</span> <span class="va">qnorm</span>, xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">3</span>, <span class="fl">3</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p><img src="graphical_evaluation_realcases_files/figure-html/unnamed-chunk-23-1.png" width="700"></p>
<p>This is also reflected in the pattern of the <em>Q-Q plot</em> of the linear model: Due to the high frequency in values between -2 and 0, the observed quantile residuals increase slower in this region relative to the standard normal quantiles. However, the low frequency of quantile residuals above zero leads to an higher increase in quantile residuals compared to the standard normal quantiles.</p>
<p>In summary, the <em>Q-Q plot</em> of the linear model has a positive curvature, bending up at both ends of the distributional tails. The censored logistic regression <code>m_hclog</code> follows more or less the reference line indicating normally distributed quantile residuals:</p>
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">q1</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/qqrplot.html">qqrplot</a></span><span class="op">(</span><span class="va">m_lm</span>, plot <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>
<span class="va">q2</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/qqrplot.html">qqrplot</a></span><span class="op">(</span><span class="va">m_hclog</span>, plot <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>
<span class="fu">ggplot2</span><span class="fu">::</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autoplot.html">autoplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">q1</span>, <span class="va">q2</span><span class="op">)</span>, colour <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">4</span><span class="op">)</span>, alpha <span class="op">=</span> <span class="fl">0.8</span>, single_graph <span class="op">=</span> <span class="cn">TRUE</span>, simint <span class="op">=</span> <span class="cn">FALSE</span>, confint <span class="op">=</span><span class="st">"line"</span><span class="op">)</span></code></pre></div>
<p><img src="graphical_evaluation_realcases_files/figure-html/unnamed-chunk-24-1.png" width="700"></p>
<p>Consistent with the pattern of right-skewed PIT residuals corresponding to a “too left-skewed” fitted distribution, a U-shaped pattern is evident in the <em>worm plot</em> of the linear model; the censored logistic is more or less flat around zero.</p>
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">w1</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/wormplot.html">wormplot</a></span><span class="op">(</span><span class="va">m_lm</span>, plot <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>
<span class="va">w2</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/wormplot.html">wormplot</a></span><span class="op">(</span><span class="va">m_hclog</span>, plot <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>
<span class="fu">ggplot2</span><span class="fu">::</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autoplot.html">autoplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">w1</span>, <span class="va">w2</span><span class="op">)</span>, colour <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">4</span><span class="op">)</span>, alpha <span class="op">=</span> <span class="fl">0.8</span>, single_graph <span class="op">=</span> <span class="cn">TRUE</span>, simint <span class="op">=</span> <span class="cn">FALSE</span>, confint <span class="op">=</span><span class="st">"line"</span><span class="op">)</span></code></pre></div>
<p><img src="graphical_evaluation_realcases_files/figure-html/unnamed-chunk-25-1.png" width="700"></p>
</div>
<div id="references" class="section level2 unnumbered">
<h2 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h2>
<div id="refs" class="references">
<div id="ref-Buuren+Fredriks:2001">
<p>Buuren, Stef van, and Miranda Fredriks. 2001. “Worm Plot: A Simple Diagnostic Device for Modelling Growth Reference Curves.” <em>Statistics in Medicine</em> 20 (8): 1259–77. <a href="https://doi.org/10.1002/sim.746">https://doi.org/10.1002/sim.746</a>.</p>
</div>
<div id="ref-Dawid:1984">
<p>Dawid, A. P. 1984. “Present Position and Potential Developments: Some Personal Views: Statistical Theory: The Prequential Approach.” <em>Journal of the Royal Statistical Society: Series A (General)</em> 147 (2): 278–92. <a href="https://doi.org/10.2307/2981683">https://doi.org/10.2307/2981683</a>.</p>
</div>
<div id="ref-Diebold+Gunther+Tay:1998">
<p>Diebold, Francis X., Todd A. Gunther, and Anthony S. Tay. 1998. “Evaluating Density Forecasts with Applications to Financial Risk Management.” <em>International Economic Review</em> 39 (4): 863–83. <a href="https://doi.org/10.2307/2527342">https://doi.org/10.2307/2527342</a>.</p>
</div>
<div id="ref-Gneiting+Balabdaoui+Raftery:2007">
<p>Gneiting, Tilmann, Fadoua Balabdaoui, and Adrian E. Raftery. 2007. “Probabilistic Forecasts, Calibration and Sharpness.” <em>Journal of the Royal Statistical Society: Series B (Methodological)</em> 69 (2): 243–68. <a href="https://doi.org/10.1111/j.1467-9868.2007.00587.x">https://doi.org/10.1111/j.1467-9868.2007.00587.x</a>.</p>
</div>
<div id="ref-Gneiting+Raftery+Westveld+Goldman:2005">
<p>Gneiting, Tilmann, Adrian E. Raftery, Anton H. Westveld, and Tom Goldman. 2005. “Calibrated Probabilistic Forecasting Using Ensemble Model Output Statistics and Minimum CRPS Estimation.” <em>Monthly Weather Review</em> 133 (5): 1098–1118. <a href="https://doi.org/http://dx.doi.org/10.1175/MWR2904.1">https://doi.org/http://dx.doi.org/10.1175/MWR2904.1</a>.</p>
</div>
<div id="ref-Kleiber+Zeileis:2016">
<p>Kleiber, Christian, and Achim Zeileis. 2016. “Visualizing Count Data Regressions Using Rootograms.” <em>The American Statistician</em> 70 (3): 296–303. <a href="https://doi.org/10.1080/00031305.2016.1173590">https://doi.org/10.1080/00031305.2016.1173590</a>.</p>
</div>
<div id="ref-Leitner+Zeileis+Hornik:2010">
<p>Leitner, Christoph, Achim Zeileis, and Kurt Hornik. 2010. “Forecasting Sports Tournaments by Ratings of (Prob)abilities: A Comparison for the EURO 2008.” <em>International Journal of Forecasting</em> 26 (3): 471–81. <a href="https://doi.org/10.1016/j.ijforecast.2009.10.001">https://doi.org/10.1016/j.ijforecast.2009.10.001</a>.</p>
</div>
<div id="ref-Messner+Mayr+Zeileis:2016">
<p>Messner, Jakob W., Georg J. Mayr, and Achim Zeileis. 2016. “Heteroscedastic Censored and Truncated Regression with crch.” <em>The R Journal</em> 8 (1): 173–81. <a href="https://doi.org/10.32614/RJ-2016-012">https://doi.org/10.32614/RJ-2016-012</a>.</p>
</div>
<div id="ref-Warton:2017">
<p>Warton, Loïc AND Wang, David I. AND Thibaut. 2017. “The Pit-Trap—a ‘Model-Free’ Bootstrap Procedure for Inference About Regression Models with Discrete, Multivariate Responses.” <em>PLOS ONE</em> 12 (7): 1–18. <a href="https://doi.org/10.1371/journal.pone.0181790">https://doi.org/10.1371/journal.pone.0181790</a>.</p>
</div>
<div id="ref-Zeileis+Leitner+Hornik:2018">
<p>Zeileis, Achim, Christoph Leitner, and Kurt Hornik. 2018. “Probabilistic Forecasts for the 2018 FIFA World Cup Based on the Bookmaker Consensus Model.” Working Paper 2018-09. Working Papers in Economics; Statistics, Research Platform Empirical; Experimental Economics, Universität Innsbruck. <a href="https://EconPapers.RePEc.org/RePEc:inn:wpaper:2018-09">https://EconPapers.RePEc.org/RePEc:inn:wpaper:2018-09</a>.</p>
</div>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Achim Zeileis, Moritz N. Lang.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
