png("crch.png", height = 75, width = 75, bg = "transparent")
par(mar = rep(0, 4))
x <- seq(-2, 3, by = 0.01)
plot(x, dlogis(x), type = "l", lwd = 1, col = "#2c2c2b", axes = FALSE, xlab = "", ylab = "")
polygon(c(x[1], x[x <= -0.5], -0.5), c(dlogis(tail(x, 1)), dlogis(x[x <= -0.5]), dlogis(tail(x, 1))), border = "#b52267", col = "#b52267", lwd = 5)
lines(x, dlogis(x), type = "l", lwd = 5, col = "#2c2c2b")
dev.off()

## png("crch-raw.png", height = 75, width = 260, bg = "transparent")
## par(mar = rep(0, 4))
## x <- seq(-0.6, 2.8, by = 0.01)
## plot(x, dlogis(x), type = "l", lwd = 7, col = "#2c2c2b", axes = FALSE, xlab = "", ylab = "", ylim = c(0, 0.26))
## polygon(c(x[1], x[x <= 0], 0), c(0, dlogis(x[x <= 0]), 0), border = "#b52267", col = "#b52267", lwd = 5)
## lines(x, dlogis(x), type = "l", lwd = 5, col = "#2c2c2b")
## ## crch: Roboto Medium 75
## dev.off()
