




abstract:
	pdflatex abstract.tex
	pdflatex abstract.tex


.PHONY: clean
clean:
	-rm abstract.aux
	-rm abstract.bbl
	-rm abstract.blg
	-rm abstract.log

.PHONY: distclean
distclean:
	make clean
	-rm abstract.pdf
